sudo: false
language: c

cache:
  directories:
  - $HOME/.stack

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.stack
  - .stack-work

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - travis_wait stack --no-terminal --skip-ghc-check setup

before_script:
  - echo "override before_script"

script:
  - travis_wait stack --no-terminal --skip-ghc-check test
