language: haskell
ghc: '8.0.2'
sudo: false

cache:
  directories:
  - '$HOME/.cabal'
  - '$HOME/.ghc'

branches:
  only:
    - 'master'

install:
  - cabal install --enable-tests

script:
  - cabal test
