resolver: nightly-2017-11-20
extra-package-dbs: []

flags:
  hakyll:
    previewServer: True
    watchServer:   True
    checkExternal: True

packages:
  - '.'
  - extra-dep: True
    location:
      git: https://github.com/jgm/pandoc.git
      commit: cf87ffe9ee87b5e908725616998724fca0d6a8fd

extra-deps:
  - hslua-module-text-0.1.2

nix:
  enable: false
  packages:
    - zlib
