resolver: nightly-2017-12-01
extra-package-dbs: []

flags:
  hakyll:
    previewServer: True
    watchServer:   True
    checkExternal: True

packages:
  - '.'
  - extra-dep: True
    location:
      git: https://github.com/jgm/pandoc.git
      commit: ecfb5a08381dcfd3eb1c586ceb6cbc3aea96a7d5

extra-deps:
  - hslua-module-text-0.1.2
  - skylighting-0.4.4.1

nix:
  enable: false
  packages:
    - zlib
