resolver: nightly-2017-11-20
extra-package-dbs: []

flags:
  hakyll:
    previewServer: True
    watchServer:   True
    checkExternal: True

packages:
  - '.'
  - extra-dep: True
    location:
      git: https://github.com/jgm/pandoc.git
      commit: 51027cff294e83957f8ee365dd296b446699c365

extra-deps:
  - hslua-module-text-0.1.2
  - skylighting-0.4.4

nix:
  enable: false
  packages:
    - zlib
